/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kaushalendra
 */
public class testframe extends javax.swing.JFrame {

    /**
     * Creates new form testframe
     */
    public testframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(362, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//
//        try {
//
//            Shop.ShopUsername = "qwerty";
//            Connection con = DatabaseConnection.getConnection();
//
////                   String UserUsername=rs.getString("UserUsername");
////                    JOptionPane.showMessageDialog(this, UserUsername);
//            Statement stmt2 = con.createStatement();
//            ResultSet rs = stmt2.executeQuery("SELECT *  \n"
//                    + "FROM   `1516289225`.`orders`\n"
//                    + "WHERE  `1516289225`.`orders`.`Shopusername` = '" + Shop.getShopUsername() + "';");
//
//            String UserUsername = "";
//       
//            rs.next();
////            UserUsername = rs.getString("UserUsername");
//           for (int i = 1; i <= 2; i++) {
//                  UserUsername = rs.getString("UserUsername");
//                String query2 = "SELECT COUNT(`1516289225`.`orders`.`UserUsername`)\n"
//                        + "FROM `1516289225`.`orders`\n"
//                        + "WHERE `1516289225`.`orders`.`UserUsername` = '" + UserUsername + "';";
//                Statement stmt3 = con.createStatement();
//                ResultSet rs2 = stmt3.executeQuery(query2);
//                int count2 = 0;
//                while (rs2.next()) {
//                    count2 = rs2.getInt("COUNT(`1516289225`.`orders`.`UserUsername`)");
//
//                }
//                stmt3.close();
//
//              
//              
//                    Shop.products[] product = new Shop.products[count2];
//                        String productNames[]=new String[count2];
//                        int QuantityOrdered[]=new int[count2];
//                        String comments=rs.getString("Comments");
//                        User userobj=new User(UserUsername);
//                        for(int j=1;j<=count2;j++)
//                        {
//                            productNames[j-1]= rs.getString("productname");
//                            QuantityOrdered[j-1]=rs.getInt("Quantity");
//                            Shop shopobj=new Shop();
//                            product[j-1]=shopobj.new products(productNames[j-1],"qwerty");
////                            JOptionPane.showMessageDialog(this,"name "+userobj.getFirstName()+ " Username" + UserUsername + " Comments" + comments+" ProductName"+product[j-1].getName()+" Quantity "+QuantityOrdered[j-1]);
//                        
//                            
//                            rs.next();
//                        }
////                        contentPanel2.add(new OrdersPanel(userobj,product,count2,QuantityOrdered,comments));
////                        contentPanel2.repaint();
////                        contentPanel2.revalidate();
////                      
////                JOptionPane.showMessageDialog(this, "Username" + UserUsername + "Username prev" + UserUsernameprev + " Comments" + comments+" ProductName"+productNames[0]+" Quantity "+QuantityOrdered[0]);
//                
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(testframe.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
