/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_CS261;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author TEJENDRA
 */
public class CurrentOrders extends javax.swing.JFrame {

    /**
     * Creates new form listUI
     */
    public CurrentOrders() {
        initComponents();
        setExtendedState(CurrentOrders.MAXIMIZED_BOTH);
        contentPanel2.setLayout(new BoxLayout(contentPanel2, BoxLayout.Y_AXIS));
       Orders obj=new Orders();
        obj.SearchShopsOrders(contentPanel2);
    }

    public void SearchShopsOrders() {
        try {
            Connection con = DatabaseConnection.getConnection();
            Statement stmt = con.createStatement();
            ResultSet rs3 = stmt.executeQuery("SELECT COUNT(DISTINCT `1516289225`.`orders`.`UserUsername`) FROM `1516289225`.`orders`;");
            int count = 0;
            while (rs3.next()) {
                count = rs3.getInt("COUNT(DISTINCT `1516289225`.`orders`.`UserUsername`)");
            }
            stmt.close();
             Statement stmt2 = con.createStatement();
            ResultSet rs = stmt2.executeQuery("SELECT *  \n"
                    + "FROM   `1516289225`.`orders`\n"
                    + "WHERE  `1516289225`.`orders`.`Shopusername` = '" + Shop.getShopUsername() + "';");
             String UserUsername = "";

            if (rs.next()) {
                UserUsername = rs.getString("UserUsername");
                
            }
            int TotalValue=0;
           for (int i = 1; i <= count; i++) {
               TotalValue=0; 
               UserUsername = rs.getString("UserUsername");
                String query2 = "SELECT COUNT(`1516289225`.`orders`.`UserUsername`)\n"
                        + "FROM `1516289225`.`orders`\n"
                        + "WHERE `1516289225`.`orders`.`UserUsername` = '" + UserUsername + "';";
                Statement stmt3 = con.createStatement();
                ResultSet rs2 = stmt3.executeQuery(query2);
                int count2 = 0;
                while (rs2.next()) {
                    count2 = rs2.getInt("COUNT(`1516289225`.`orders`.`UserUsername`)");

                }
                stmt3.close();

              
              
                    Shop.products[] product = new Shop.products[count2];
                        String productNames[]=new String[count2];
                        int QuantityOrdered[]=new int[count2];
                        String comments=rs.getString("Comments");
                        User userobj=new User(UserUsername);
                        for(int j=1;j<=count2;j++)
                        {
                            productNames[j-1]= rs.getString("productname");
                            QuantityOrdered[j-1]=rs.getInt("Quantity");
                            Shop shopobj=new Shop();
                            product[j-1]=shopobj.new products(productNames[j-1],Shop.getShopUsername());
//                            JOptionPane.showMessageDialog(this,"name "+userobj.getFirstName()+ " Username" + UserUsername + " Comments" + comments+" ProductName"+product[j-1].getName()+" Quantity "+QuantityOrdered[j-1]);
                        TotalValue+=QuantityOrdered[j-1]*product[j-1].getRetailPrice();
                            rs.next();
                        }
                        contentPanel2.add(new OrdersPanel(userobj,product,count2,QuantityOrdered,comments,TotalValue));
                        contentPanel2.repaint();
                        contentPanel2.revalidate();
//                      
//                JOptionPane.showMessageDialog(this, "Username" + UserUsername + "Username prev" + UserUsernameprev + " Comments" + comments+" ProductName"+productNames[0]+" Quantity "+QuantityOrdered[0]);
                
            }

             

        } catch (HeadlessException | SQLException ex) {
            Logger.getLogger(CurrentOrders.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        contentPanel2 = new javax.swing.JPanel();
        Home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        contentPanel2.setPreferredSize(new java.awt.Dimension(1200, 357));

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPanel2Layout = new javax.swing.GroupLayout(contentPanel2);
        contentPanel2.setLayout(contentPanel2Layout);
        contentPanel2Layout.setHorizontalGroup(
            contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanel2Layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addComponent(Home)
                .addContainerGap(1093, Short.MAX_VALUE))
        );
        contentPanel2Layout.setVerticalGroup(
            contentPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanel2Layout.createSequentialGroup()
                .addComponent(Home)
                .addGap(0, 683, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(contentPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1566, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new shop_ui().setVisible(true);
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrentOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrentOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrentOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrentOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrentOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JPanel contentPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
